services:
  extractor:
    build: .
    image: notebookum-extractor:v1.0.0
    restart: unless-stopped
    deploy:
      replicas: 1
    networks:
      notebookum-network:
        aliases:
          - extractor.universidad.localhost
    environment:
      - CONSUL_URL=http://consul:8500
      - CONSUL_TOKEN=${CONSUL_TOKEN:-}

networks:
  notebookum-network:
    external: true
